# Generated by Django 4.1 on 2022-09-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_title', models.CharField(max_length=200)),
                ('building_description', models.TextField(max_length=450)),
                ('type', models.IntegerField(choices=[(1, 'Management'), (2, 'Commercial'), (3, 'Military Or Adventuring'), (4, 'Educational')])),
                ('level', models.IntegerField(default=0)),
                ('cost', models.IntegerField()),
                ('revenue', models.IntegerField(blank=True, default=0)),
                ('pop_mod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_name', models.CharField(max_length=200)),
                ('settlement_level', models.IntegerField(choices=[(1, 'Hamlet'), (2, 'Village'), (3, 'Tiny Town'), (4, 'Big Town'), (5, 'City'), (6, 'Major City'), (7, 'Metropolis')])),
                ('settlement_location', models.CharField(max_length=200)),
                ('starting_population', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_descr', models.CharField(max_length=200)),
                ('item_URL', models.URLField()),
                ('item_cost', models.IntegerField(default=50)),
                ('item_stock', models.IntegerField(default=1)),
                ('item_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building')),
            ],
        ),
        migrations.CreateModel(
            name='Population_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_pos_change', models.IntegerField(default=0)),
                ('pop_neg_change', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.settlement')),
            ],
            options={
                'verbose_name_plural': 'Population changes',
            },
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_change', models.IntegerField(default=0)),
                ('neg_change', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.settlement')),
            ],
            options={
                'verbose_name_plural': 'Funds',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_desc', models.TextField(max_length=450)),
                ('event_effect', models.TextField(max_length=450)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200)),
                ('character_function', models.CharField(max_length=200)),
                ('character_first_contact', models.CharField(max_length=200)),
                ('character_information', models.TextField(max_length=450)),
                ('character_added_information', models.TextField(max_length=450)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.settlement')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.settlement'),
        ),
        migrations.AddField(
            model_name='building',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.character'),
        ),
    ]
